### ISSUE TITLE
func-style is really annoying

### ISSUE THREAD

**Issue by gplancke** [SimpliField/eslint-config-simplifield#11]
Especially when var must be placed at top of file.

If I want to assign a function to a variable.
1. I have to declare a variable
2. After all variables, I can create a function.
3. THEN and only then, I can assign my function to my variable.

The least would be to allow mixing variable and function declaration.

**Comment by nfroidure** [comment]
Naming the function should prevent the need to set it to a variable and keep the variable declarations and functions declarations separated.

**Comment by gplancke** [comment]
Yeah but it put function declaration to the end, separated from the actual logic.
Especially when you use curried functions, you might want to set a variable to a partially applied function which if you follow our lint configuration will be declared far after.

Mixing declarations types should really be possible, what advantage for not allowing so?

**Comment by nfroidure** [comment]
Mainly clarity. In a function, you should not have more than 10 to 20 different local names (this is a great maximum imo). Given this, i assume it is better to group variables declarations and functions declarations.

Also, functions declarations mostly take several lines when variables takes only one or rarely a few more.

Maybe an example could illustrate the problem you described before better, i can't figure it out well to be honest. When you curry a function, isn't it a simple variable declaration instead of a function declaration? Or maybe you define the curryed function in the same scope than the declared function but if it is the case, i think you shouldn't. "Base" functions should sit in their own module since nothing impeach you to do so, or, at worst, in an upper scope (often the root scope of the current module).

On the other hand, i'm not closed to changes since disabling this rule would not disturb me to continue grouping my variable declarations together.  Maybe that we could, at least, turn this rule to a simple warning.

**Comment by nfroidure** [comment]
Just thought about it, but great names can also resolve the issue. If the name describe the function intents, no need to look at the implementation at the variable declaration level.

**Comment by xavhan** [comment]
+1
good naming prevent looking (at first) at the implem
